trigger:
- main

pool:
  name: reema

steps:
- task: Maven@4
  displayName: 'Build and test with Maven'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
